import React from 'react';
import { ShoppingBag, Car, ShoppingCart, Gift, Plane, Home, BookOpen, Coffee } from 'lucide-react';

export const getIcon = (name: string) => {
    switch (name) {
        case 'ShoppingBag': return <ShoppingBag size={20} />;
        case 'Car': return <Car size={20} />;
        case 'ShoppingCart': return <ShoppingCart size={20} />;
        case 'Gift': return <Gift size={20} />;
        case 'Plane': return <Plane size={20} />;
        case 'Home': return <Home size={20} />;
        case 'BookOpen': return <BookOpen size={20} />;
        default: return <Coffee size={20} />;
    }
};

// List of available brands with cashback percentages
export const BRANDS_DATA = [
    { name: "3Bee", percentage: 16.0, categories: ["regali"] },
    { name: "Abbonamenti", percentage: 8.0, categories: ["regali"] },
    { name: "Abbonamenti.it", percentage: 5.63, categories: ["regali"] },
    { name: "Academia", percentage: 17.0, categories: ["regali"] },
    { name: "Acqua & Sapone", percentage: 5.0, categories: ["igiene", "casa"] },
    { name: "Activitygift", percentage: 7.0, categories: ["regali"] },
    { name: "ADIDAS", percentage: 8.64, categories: ["abb"] },
    { name: "ADOBE", percentage: 14.4, categories: ["aff_int"] },
    { name: "AGODA", percentage: 4.32, categories: ["treni"] },
    { name: "AIR FRANCE", percentage: 0.72, categories: ["treni"] },
    { name: "Airbnb", percentage: 3.5, categories: ["treni", "regali"] },
    { name: "ALI'", percentage: 2.63, categories: ["alim"] },
    { name: "AliExpress", percentage: 6.92, categories: ["aff_int"] },
    { name: "Allianz Assicurazioni", percentage: 0, fixedAmount: 13, categories: ["aff_int"] },
    { name: "Almasicily", percentage: 13.0, categories: ["alim"] },
    { name: "Alpitour", percentage: 12.0, categories: ["treni"] },
    { name: "AMICAFARMACIA", percentage: 3.6, categories: ["igiene"] },
    { name: "Amazon.it", percentage: 1.87, categories: ["alim", "igiene", "abb", "regali", "casa", "school", "md"] },
    { name: "API IP", percentage: 2.5, categories: ["carb"] },
    { name: "Arcaplanet", percentage: 3.5, categories: ["casa"] },
    { name: "ARCAPLANET", percentage: 2.88, categories: ["casa"] },
    { name: "ARMANI EXCHANGE", percentage: 5.76, categories: ["abb"] },
    { name: "AS Roma", percentage: 3.75, categories: ["regali", "abb"] },
    { name: "ASICS", percentage: 5.76, categories: ["abb"] },
    { name: "Asos", percentage: 4.88, categories: ["abb", "regali"] },
    { name: "AVG", percentage: 21.6, categories: ["aff_int"] },
    { name: "AVIRA", percentage: 21.6, categories: ["aff_int"] },
    { name: "AVIS", percentage: 3.6, categories: ["treni"] },
    { name: "Avon", percentage: 7.0, categories: ["aff_int"] },
    { name: "AW LAB", percentage: 4.0, categories: ["abb"] },
    { name: "Axa", percentage: 12.0, categories: ["aff_int"] },
    { name: "Babbel", percentage: 0, fixedAmount: 60, categories: ["aff_int"] },
    { name: "Basko", percentage: 4.0, categories: ["alim"] },
    { name: "BASKO", percentage: 2.78, categories: ["alim"] },
    { name: "Bata", percentage: 4.0, categories: ["abb"] },
    { name: "BAUKNECHT", percentage: 3.6, categories: ["casa"] },
    { name: "Bennet", percentage: 3.0, categories: ["alim"] },
    { name: "BERNABEI", percentage: 4.32, categories: ["alim"] },
    { name: "Best Western Hotels & Resorts", percentage: 4.13, categories: ["regali", "treni"] },
    { name: "BIALETTI", percentage: 4.32, categories: ["casa"] },
    { name: "Bidoo", percentage: 0, fixedAmount: 5, categories: ["aff_int"] },
    { name: "Bimbostore", percentage: 6.0, categories: ["regali"] },
    { name: "Bitdefender", percentage: 30.0, categories: ["aff_int"] },
    { name: "BITDEFENDER", percentage: 28.8, categories: ["aff_int"] },
    { name: "BITIBA", percentage: 2.88, categories: ["casa"] },
    { name: "Booking.com", percentage: 3.6, categories: ["treni", "regali"] },
    { name: "Borbonese", percentage: 10.0, categories: ["abb"] },
    { name: "Boscolo", percentage: 12.38, categories: ["regali", "treni"] },
    { name: "Bottega Verde", percentage: 3.38, categories: ["igiene", "regali"] },
    { name: "Brico io", percentage: 4.0, categories: ["casa"] },
    { name: "Brico Io", percentage: 4.5, categories: ["casa", "regali"] },
    { name: "Bricocenter", percentage: 2.62, categories: ["casa", "regali"] },
    { name: "British School", percentage: 13.0, categories: ["regali"] },
    { name: "BTX Bar", percentage: 12.0, categories: ["regali"] },
    { name: "BUDGET", percentage: 3.6, categories: ["treni"] },
    { name: "Buono Enilive Digitale", percentage: 1.88, categories: ["carb"] },
    { name: "Buono Enilive Servito Digitale", percentage: 2.25, categories: ["carb"] },
    { name: "Caffe Borbone", percentage: 10.0, categories: ["alim"] },
    { name: "Calliope", percentage: 5.0, categories: ["abb", "regali"] },
    { name: "CALLMEWINE", percentage: 3.6, categories: ["alim"] },
    { name: "Calzedonia", percentage: 3.38, categories: ["abb", "regali"] },
    { name: "CANON", percentage: 1.44, categories: ["tech"] },
    { name: "Carrefour", percentage: 3.5, categories: ["alim"] },
    { name: "Carriereit", percentage: 29.0, categories: ["regali"] },
    { name: "Casa Folino 1962", percentage: 10.0, categories: ["casa"] },
    { name: "CC Fuentes", percentage: 2.5, categories: ["regali"] },
    { name: "Cerox", percentage: 12.0, categories: ["regali"] },
    { name: "Chicco", percentage: 4.88, categories: ["abb", "regali", "school"] },
    { name: "Cilento Outlet", percentage: 2.0, categories: ["abb"] },
    { name: "CityLife Shopping District", percentage: 2.0, categories: ["abb"] },
    { name: "ClinGo", percentage: 12.0, categories: ["regali"] },
    { name: "CLINIQUE", percentage: 5.76, categories: ["igiene"] },
    { name: "Coccinelle", percentage: 3.0, categories: ["abb", "regali"] },
    { name: "Coin", percentage: 6.0, categories: ["abb", "regali", "casa"] },
    { name: "Conad", percentage: 1.69, categories: ["alim"] },
    { name: "CONVERSE", percentage: 5.76, categories: ["abb"] },
    { name: "CTS Supermercati", percentage: 3.0, categories: ["alim"] },
    { name: "DAZN FULL", percentage: 3.38, categories: ["regali"] },
    { name: "Decathlon", percentage: 4.13, categories: ["regali", "abb"] },
    { name: "Deco", percentage: 6.0, categories: ["alim"] },
    { name: "DEGUSTABOX", percentage: 7.2, categories: ["alim"] },
    { name: "DELL", percentage: 2.16, categories: ["tech"] },
    { name: "DELIVEROO", percentage: 1.44, categories: ["alim"] },
    { name: "Deliveroo", percentage: 3.5, categories: ["alim"] },
    { name: "Despar Nordest", percentage: 2.25, categories: ["alim"] },
    { name: "Dietetic", percentage: 13.0, categories: ["regali"] },
    { name: "DisneyPlus Premium", percentage: 2.63, categories: ["regali"] },
    { name: "DISNEY STORE", percentage: 2.16, categories: ["regali"] },
    { name: "doc Supermercati", percentage: 3.0, categories: ["alim"] },
    { name: "DoFit", percentage: 12.0, categories: ["regali"] },
    { name: "Doppelganger", percentage: 4.88, categories: ["abb", "regali"] },
    { name: "Douglas", percentage: 5.5, categories: ["igiene", "regali"] },
    { name: "Dr Beckmann", percentage: 13.0, categories: ["casa"] },
    { name: "Du Pareil Au Meme", percentage: 8.0, categories: ["abb", "regali"] },
    { name: "Eataly", percentage: 3.38, categories: ["alim", "regali"] },
    { name: "Eathlon", percentage: 15.0, categories: ["alim"] },
    { name: "EBAY", percentage: 1.44, categories: ["regali"] },
    { name: "Ecobnb", percentage: 4.13, categories: ["regali", "treni", "casa"] },
    { name: "EDREAMS", percentage: 4.32, categories: ["treni"] },
    { name: "EFARMA", percentage: 3.6, categories: ["igiene"] },
    { name: "EKOM", percentage: 2.78, categories: ["alim", "md"] },
    { name: "Elite Supermercati", percentage: 3.5, categories: ["alim"] },
    { name: "ENI", percentage: 2.5, categories: ["carb"] },
    { name: "EquoTube", percentage: 12.0, categories: ["regali"] },
    { name: "EsserBella Profumerie", percentage: 3.75, categories: ["igiene", "regali"] },
    { name: "ESTÉE LAUDER", percentage: 5.76, categories: ["igiene"] },
    { name: "EUROPCAR", percentage: 5.76, categories: ["treni"] },
    { name: "Eurospin", percentage: 1.0, categories: ["alim"] },
    { name: "EXPEDIA", percentage: 4.32, categories: ["treni"] },
    { name: "Expert", percentage: 1.88, categories: ["regali", "casa", "tech"] },
    { name: "Falconeri", percentage: 4.88, categories: ["abb", "regali"] },
    { name: "FAO Schwarz", percentage: 6.5, categories: ["regali"] },
    { name: "FARMACIA IGEA", percentage: 3.6, categories: ["igiene"] },
    { name: "FARMACIA LORETO", percentage: 3.6, categories: ["igiene"] },
    { name: "Feltrinelli", percentage: 7.0, categories: ["school", "regali", "tech"] },
    { name: "Fever Candlelight", percentage: 8.0, categories: ["regali"] },
    { name: "Fiorentini", percentage: 10.0, categories: ["alim"] },
    { name: "Fitness da Divano", percentage: 13.0, categories: ["regali"] },
    { name: "Fitness da Scrivania", percentage: 13.0, categories: ["regali"] },
    { name: "Flightgift", percentage: 4.0, categories: ["regali", "treni"] },
    { name: "Flixbus", percentage: 5.0, categories: ["treni", "regali"] },
    { name: "FlixBus", percentage: 3.6, categories: ["treni", "regali"] },
    { name: "Folletto", percentage: 6.0, categories: ["aff_int"] },
    { name: "Foot Locker", percentage: 7.5, categories: ["abb", "regali"] },
    { name: "Franciacorta Village", percentage: 2.0, categories: ["abb"] },
    { name: "Gamelife", percentage: 4.0, categories: ["regali", "tech"] },
    { name: "GAMESTOP", percentage: 1.44, categories: ["regali"] },
    { name: "GetYourGuide", percentage: 5.25, categories: ["regali", "treni"] },
    { name: "Gioielli Dop", percentage: 12.0, categories: ["regali"] },
    { name: "Giunti al Punto", percentage: 4.13, categories: ["school", "regali"] },
    { name: "Global Experiences Card", percentage: 5.25, categories: ["regali"] },
    { name: "Global Hotel Card", percentage: 5.25, categories: ["regali", "treni"] },
    { name: "GLOVO", percentage: 1.44, categories: ["alim"] },
    { name: "Google Play IT", percentage: 2.25, categories: ["regali", "tech"] },
    { name: "Grand Vision Italy", percentage: 4.5, categories: ["regali"] },
    { name: "GROUPON", percentage: 11.52, categories: ["regali"] },
    { name: "Guess", percentage: 4.13, categories: ["abb", "regali"] },
    { name: "H&M", percentage: 4.88, categories: ["abb", "regali"] },
    { name: "Hawaii Moka", percentage: 12.0, categories: ["alim"] },
    { name: "HELLO FRESH", percentage: 14.4, categories: ["alim"] },
    { name: "HERTZ", percentage: 3.6, categories: ["treni"] },
    { name: "Ho Mobile", percentage: 0, fixedAmount: 11, categories: ["aff_int"] },
    { name: "Hoepli.it", percentage: 4.88, categories: ["school", "regali"] },
    { name: "Hotelgift", percentage: 7.0, categories: ["regali", "treni"] },
    { name: "HOTELS.COM", percentage: 4.32, categories: ["treni"] },
    { name: "HotelsGift", percentage: 6.0, categories: ["regali", "treni"] },
    { name: "HP", percentage: 2.16, categories: ["tech"] },
    { name: "HUAWEI", percentage: 2.16, categories: ["tech"] },
    { name: "I primi 3 mesi di Sky TV + Sky Calcio + Sky Sport", percentage: 3.38, categories: ["regali"] },
    { name: "I primi 3 mesi di Sky TV e Netflix (Intrattenimento plus) + Sky Cinema", percentage: 3.38, categories: ["regali"] },
    { name: "IBERIA LÍNEAS AÉREAS", percentage: 3.75, categories: ["treni"] },
    { name: "IBS", percentage: 6.0, categories: ["school", "regali"] },
    { name: "IBS.it", percentage: 4.5, categories: ["school", "regali"] },
    { name: "ideaShopping", percentage: 1.88, categories: ["alim", "igiene", "abb", "regali", "casa", "school", "md", "treni"] },
    { name: "IKEA", percentage: 6.5, categories: ["casa", "regali"] },
    { name: "Il Gigante", percentage: 4.75, categories: ["alim"] },
    { name: "Il Viaggiator Goloso", percentage: 2.5, categories: ["alim"] },
    { name: "ILLY", percentage: 4.32, categories: ["casa"] },
    { name: "INDESIT", percentage: 3.6, categories: ["casa"] },
    { name: "Interflora", percentage: 8.5, categories: ["regali"] },
    { name: "Intimissimi", percentage: 3.38, categories: ["abb", "regali"] },
    { name: "Io sono te", percentage: 8.0, categories: ["regali"] },
    { name: "IP", percentage: 1.88, categories: ["carb"] },
    { name: "Iper", percentage: 5.0, categories: ["alim"] },
    { name: "Iper La grande i", percentage: 3.0, categories: ["alim"] },
    { name: "Iper Tosano", percentage: 4.0, categories: ["alim"] },
    { name: "Iperal", percentage: 2.25, categories: ["alim"] },
    { name: "ITA AIRWAYS", percentage: 3.38, categories: ["treni", "regali"] },
    { name: "Italo", percentage: 2.78, categories: ["treni", "regali"] },
    { name: "Italmark", percentage: 3.5, categories: ["alim"] },
    { name: "Japal", percentage: 12.0, categories: ["regali"] },
    { name: "JD SPORTS", percentage: 3.38, categories: ["abb"] },
    { name: "JUST EAT", percentage: 1.44, categories: ["alim"] },
    { name: "Kasanova", percentage: 3.0, categories: ["casa", "regali"] },
    { name: "Kaspersky", percentage: 5.0, categories: ["aff_int"] },
    { name: "Kena Mobile", percentage: 0, fixedAmount: 34, categories: ["aff_int"] },
    { name: "Kiabi", percentage: 3.38, categories: ["abb"] },
    { name: "KIKO MILANO", percentage: 5.76, categories: ["igiene"] },
    { name: "Kimbo", percentage: 10.0, categories: ["alim"] },
    { name: "KIWI.COM", percentage: 2.16, categories: ["treni"] },
    { name: "KRUPS", percentage: 4.32, categories: ["casa"] },
    { name: "L'ERBOLARIO", percentage: 3.0, categories: ["igiene", "regali"] },
    { name: "La Repubblica", percentage: 0, fixedAmount: 12, categories: ["aff_int"] },
    { name: "La Stampa", percentage: 0, fixedAmount: 12, categories: ["aff_int"] },
    { name: "LAGOSTINA", percentage: 4.32, categories: ["casa"] },
    { name: "Lastminute", percentage: 7.0, categories: ["regali", "treni"] },
    { name: "LAVAZZA", percentage: 4.32, categories: ["casa"] },
    { name: "Le Conserve della Nonna", percentage: 12.0, categories: ["alim"] },
    { name: "LEGO", percentage: 4.13, categories: ["regali"] },
    { name: "LENOVO", percentage: 2.16, categories: ["tech"] },
    { name: "LIU JO", percentage: 5.76, categories: ["abb"] },
    { name: "Libraccio", percentage: 6.0, categories: ["school", "regali"] },
    { name: "Libraccio.it", percentage: 4.5, categories: ["school", "regali"] },
    { name: "LOGITRAVEL", percentage: 2.88, categories: ["treni"] },
    { name: "LOOKFANTASTIC", percentage: 5.76, categories: ["igiene"] },
    { name: "LUFTHANSA", percentage: 0.72, categories: ["treni"] },
    { name: "Luxury Zone", percentage: 4.0, categories: ["regali"] },
    { name: "Lyca Mobile", percentage: 0, fixedAmount: 5, categories: ["aff_int"] },
    { name: "MAGGIORE", percentage: 3.6, categories: ["treni"] },
    { name: "Maisons du Monde", percentage: 7.5, categories: ["casa", "regali"] },
    { name: "Mantova Village", percentage: 2.0, categories: ["abb"] },
    { name: "Marionnaud Paris", percentage: 4.87, categories: ["igiene", "regali"] },
    { name: "Martinelli Supermercati", percentage: 3.5, categories: ["alim"] },
    { name: "MAXI DI", percentage: 2.25, categories: ["alim"] },
    { name: "MCAFEE", percentage: 21.6, categories: ["aff_int"] },
    { name: "MD", percentage: 3.0, categories: ["alim", "md"] },
    { name: "MediaWorld", percentage: 1.08, categories: ["regali", "casa", "tech"] },
    { name: "Mediaworld", percentage: 2.5, categories: ["regali", "casa", "tech"] },
    { name: "Megamark", percentage: 4.0, categories: ["alim"] },
    { name: "Mercatò", percentage: 2.25, categories: ["alim"] },
    { name: "MICHAEL KORS", percentage: 5.76, categories: ["abb"] },
    { name: "Microsoft 365", percentage: 13.0, categories: ["regali"] },
    { name: "Migross", percentage: 3.0, categories: ["alim"] },
    { name: "Miriade", percentage: 12.0, categories: ["abb"] },
    { name: "Mister Magic", percentage: 12.0, categories: ["casa"] },
    { name: "MONCLICK", percentage: 1.44, categories: ["tech"] },
    { name: "Mondadori Store", percentage: 4.13, categories: ["school", "regali", "tech"] },
    { name: "MORELLATO", percentage: 5.76, categories: ["regali"] },
    { name: "MOSCHINO", percentage: 5.76, categories: ["abb"] },
    { name: "MOULINEX", percentage: 4.32, categories: ["casa"] },
    { name: "MYTOYS", percentage: 2.16, categories: ["regali"] },
    { name: "MyGiftBox Experience", percentage: 19.0, categories: ["regali"] },
    { name: "MyGiftCardSquare", percentage: 1.75, categories: ["regali"] },
    { name: "MyGiftCardSquare First", percentage: 2.5, categories: ["regali"] },
    { name: "NaturaSi", percentage: 3.75, categories: ["alim"] },
    { name: "Nau", percentage: 7.0, categories: ["abb"] },
    { name: "Nespresso", percentage: 5.76, categories: ["aff_int"] },
    { name: "NEW BALANCE", percentage: 5.76, categories: ["abb"] },
    { name: "Nike", percentage: 3.0, categories: ["abb", "regali"] },
    { name: "Nintendo eShop", percentage: 8.0, categories: ["regali", "tech"] },
    { name: "Nintendo Switch Online", percentage: 10.0, categories: ["regali", "tech"] },
    { name: "Nord Vpn", percentage: 40.0, categories: ["aff_int"] },
    { name: "NORTON", percentage: 28.8, categories: ["aff_int"] },
    { name: "NOTINO", percentage: 3.6, categories: ["igiene"] },
    { name: "Old Wild West", percentage: 3.0, categories: ["alim"] },
    { name: "OPODO", percentage: 4.32, categories: ["treni"] },
    { name: "Orphea", percentage: 12.0, categories: ["casa"] },
    { name: "OVS", percentage: 7.5, categories: ["abb", "regali"] },
    { name: "Palmanova Village", percentage: 2.0, categories: ["abb"] },
    { name: "Pam Panorama", percentage: 2.25, categories: ["alim"] },
    { name: "Panarello", percentage: 12.0, categories: ["alim"] },
    { name: "Panda security", percentage: 35.0, categories: ["aff_int"] },
    { name: "PANDORA", percentage: 4.32, categories: ["regali"] },
    { name: "PATRIZIA PEPE", percentage: 5.76, categories: ["abb"] },
    { name: "Penny.", percentage: 3.38, categories: ["alim", "md"] },
    { name: "Petti", percentage: 10.0, categories: ["alim"] },
    { name: "Pewex", percentage: 4.0, categories: ["alim"] },
    { name: "PHILIPS", percentage: 3.6, categories: ["casa"] },
    { name: "Pim", percentage: 3.75, categories: ["alim"] },
    { name: "PINKO", percentage: 5.76, categories: ["abb"] },
    { name: "Piquadro.com", percentage: 8.63, categories: ["regali", "abb"] },
    { name: "PittaRosso", percentage: 4.5, categories: ["abb", "regali"] },
    { name: "PlayStation", percentage: 7.5, categories: ["regali", "tech"] },
    { name: "Podovis", percentage: 12.0, categories: ["igiene"] },
    { name: "Prenatal", percentage: 6.0, categories: ["regali"] },
    { name: "Primark", percentage: 3.75, categories: ["abb", "regali"] },
    { name: "Profumeria Ideale", percentage: 10.0, categories: ["igiene"] },
    { name: "Puglia Village", percentage: 2.0, categories: ["abb"] },
    { name: "PUMA", percentage: 7.2, categories: ["abb"] },
    { name: "Q8", percentage: 2.5, categories: ["carb"] },
    { name: "QC SPA", percentage: 5.62, categories: ["regali"] },
    { name: "Ray-Ban", percentage: 4.13, categories: ["abb", "regali"] },
    { name: "REDCARE", percentage: 5.76, categories: ["igiene"] },
    { name: "REEBOK", percentage: 7.2, categories: ["abb"] },
    { name: "RENTALCARS.COM", percentage: 4.32, categories: ["treni"] },
    { name: "Rinascimento", percentage: 5.5, categories: ["abb", "regali"] },
    { name: "Rituals", percentage: 6.38, categories: ["igiene", "regali"] },
    { name: "Roadhouse", percentage: 7.5, categories: ["alim"] },
    { name: "Roblox", percentage: 8.0, categories: ["regali", "tech"] },
    { name: "Rossetto", percentage: 3.75, categories: ["alim"] },
    { name: "ROWENTA", percentage: 4.32, categories: ["casa"] },
    { name: "Salmoiraghi & Vigano'", percentage: 4.13, categories: ["regali"] },
    { name: "Salute Semplice", percentage: 7.88, categories: ["regali", "igiene"] },
    { name: "SAMSUNG", percentage: 2.16, categories: ["tech"] },
    { name: "San Carlo", percentage: 12.0, categories: ["alim"] },
    { name: "Scarpe&Scarpe", percentage: 2.63, categories: ["abb", "regali"] },
    { name: "Sephora", percentage: 4.13, categories: ["igiene", "regali"] },
    { name: "SHEIN", percentage: 5.76, categories: ["aff_int"] },
    { name: "Signorvino", percentage: 4.13, categories: ["regali", "alim"] },
    { name: "SIXT", percentage: 4.32, categories: ["treni"] },
    { name: "Smart Tales", percentage: 26.0, categories: ["regali"] },
    { name: "Smartbox", percentage: 8.5, categories: ["regali"] },
    { name: "Snowit", percentage: 6.0, categories: ["treni"] },
    { name: "SODASTREAM", percentage: 5.76, categories: ["casa"] },
    { name: "Storytel", percentage: 5.0, categories: ["regali"] },
    { name: "STROILI ORO", percentage: 5.76, categories: ["regali"] },
    { name: "Supermercati Dem", percentage: 3.0, categories: ["alim"] },
    { name: "Supermercati Piccolo", percentage: 3.0, categories: ["alim"] },
    { name: "SuperConveniente", percentage: 5.5, categories: ["alim"] },
    { name: "Swarovski", percentage: 7.13, categories: ["regali"] },
    { name: "Tamoil", percentage: 2.5, categories: ["carb"] },
    { name: "Tannico.it", percentage: 4.88, categories: ["regali", "alim"] },
    { name: "TEFAL", percentage: 4.32, categories: ["casa"] },
    { name: "Telepass", percentage: 0, fixedAmount: 25, categories: ["aff_int"] },
    { name: "TEMU", percentage: 13.92, categories: ["abb"] },
    { name: "Terranova", percentage: 6.0, categories: ["abb", "regali"] },
    { name: "Tezenis", percentage: 3.38, categories: ["abb", "regali"] },
    { name: "TheFork", percentage: 5.0, categories: ["alim"] },
    { name: "Thun", percentage: 8.0, categories: ["aff_int"] },
    { name: "Tigotà", percentage: 4.13, categories: ["igiene", "casa"] },
    { name: "TIGROS", percentage: 3.5, categories: ["alim"] },
    { name: "Todis", percentage: 1.88, categories: ["alim"] },
    { name: "tomarket", percentage: 2.5, categories: ["alim"] },
    { name: "TOYS CENTER", percentage: 4.5, categories: ["regali", "school"] },
    { name: "Toys", percentage: 6.0, categories: ["regali"] },
    { name: "Travelcard by Inspire", percentage: 5.0, categories: ["regali"] },
    { name: "Trenitalia", percentage: 3.38, categories: ["treni", "regali"] },
    { name: "TRIPADVISOR", percentage: 2.88, categories: ["treni"] },
    { name: "Trony", percentage: 1.65, categories: ["regali", "casa", "tech"] },
    { name: "TRUSSARDI", percentage: 7.2, categories: ["abb"] },
    { name: "Tuti", percentage: 10.0, categories: ["regali"] },
    { name: "Twitch", percentage: 2.25, categories: ["regali", "tech"] },
    { name: "UBER", percentage: 2.4, categories: ["treni"] },
    { name: "UBER EATS", percentage: 1.44, categories: ["alim"] },
    { name: "Unes", percentage: 3.5, categories: ["alim"] },
    { name: "Unicomm", percentage: 2.25, categories: ["alim"] },
    { name: "Unieuro", percentage: 3.0, categories: ["regali", "casa", "tech"] },
    { "name": "Uni salute", percentage: 0, fixedAmount: 26.93, categories: ["aff_int"] },
    { name: "United Colors of Benetton", percentage: 3.75, categories: ["abb"] },
    { name: "UPIM", percentage: 3.38, categories: ["abb"] },
    { name: "UTravel", percentage: 5.25, categories: ["regali", "treni"] },
    { name: "Valdichiana Village", percentage: 2.0, categories: ["abb"] },
    { name: "Valsoia", percentage: 12.0, categories: ["alim"] },
    { name: "VANS", percentage: 4.32, categories: ["abb"] },
    { name: "Venchi", percentage: 4.13, categories: ["regali", "alim"] },
    { name: "Veratour", percentage: 0, fixedAmount: 21, categories: ["aff_int"] },
    { name: "VERY MOBILE", percentage: 0, fixedAmount: 15, categories: ["aff_int"] },
    { name: "VINOPURE", percentage: 5.76, categories: ["alim"] },
    { name: "VINO75", percentage: 3.6, categories: ["alim"] },
    { name: "VISTASì", percentage: 4.13, categories: ["regali"] },
    { name: "Vitavigor", percentage: 13.0, categories: ["alim"] },
    { name: "Volagratis", percentage: 8.0, categories: ["treni", "regali"] },
    { name: "VUELING", percentage: 1.44, categories: ["treni"] },
    { name: "Walber", percentage: 2.0, categories: ["alim"] },
    { name: "Wallife", percentage: 12.0, categories: ["regali"] },
    { name: "WeRoad", percentage: 5.63, categories: ["regali", "treni"] },
    { name: "WHIRLPOOL", percentage: 3.6, categories: ["casa"] },
    { name: "WINEOWINE", percentage: 5.76, categories: ["alim"] },
    { name: "Wondershare", percentage: 30.0, categories: ["aff_int"] },
    { name: "WYCON COSMETICS", percentage: 5.76, categories: ["igiene"] },
    { name: "Xbox", percentage: 10.5, categories: ["regali", "tech"] },
    { name: "XBOX Live", percentage: 5.63, categories: ["regali", "tech"] },
    { name: "YEPRICE", percentage: 1.44, categories: ["tech"] },
    { name: "Yeppon", percentage: 3.5, categories: ["tech"] },
    { name: "Zalando", percentage: 8.0, categories: ["abb", "regali"] },
    { name: "Zoologos", percentage: 7.0, categories: ["regali", "casa"] },
    { name: "ZOOPLUS", percentage: 2.88, categories: ["casa"] }
].sort((a, b) => a.name.localeCompare(b.name));

